# Config

SERVER_PORT = 9020
connections = 0
MAX_ROUND = 100000
BATCHING = 5
NUM_BUCKETS = 100
NUMBER_NODES = 3

#encryption global variables
GLOBAL_SALT = b"vuvuzela protocol v1"
GLOBAL_KEY_LEN = 32
GLOBAL_MESSAGE_LEN = 256
GLOBAL_ENCRYPTED_LEN = 468